### ISSUE TITLE
能否支持 UTF8 编码？

### ISSUE THREAD

**Issue by iflyingboots** [JohnWong/python-tool#1]
现在默认是 GBK 编码，能否给个选项（比如 `?coding=utf8`）来返回 UTF8 编码？

十分感谢。

**Comment by JohnWong** [comment]
好的。今天着手改造一下

**Comment by JohnWong** [comment]
Finished，如果有bug欢迎反馈。

**Comment by iflyingboots** [comment]
Thanks.

不过貌似这里有个笔误：`使用方法:/gep?ip={ip}`

gep -> geo

**Comment by iflyingboots** [comment]
另外，如果加上了 `type=json`  参数，最好能把  `Content-Type` 由 `text/html` 改成 `application/json`。这样比较符合标准。

再次感谢。 :+1:

**Comment by JohnWong** [comment]
没注意到唉，已经修改了。谢谢！
